version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 5050:8080

  cache:
    image: redis
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - cache_data:/data

volumes:
  postgres_data:
  cache_data:
